// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4SOU4yyAUjH4DxYWblcTvxpv9lmn6yU',
    appId: '1:162244151198:android:ab09926c5691c12d45f88f',
    messagingSenderId: '162244151198',
    projectId: 'hooked-fangtagebuch',
    storageBucket: 'hooked-fangtagebuch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdlvZ7_sQht4NKD9wsJR7uwcLByCluH3o',
    appId: '1:162244151198:ios:8462d1a7a47ed21445f88f',
    messagingSenderId: '162244151198',
    projectId: 'hooked-fangtagebuch',
    storageBucket: 'hooked-fangtagebuch.firebasestorage.app',
    androidClientId: '162244151198-02qd0nfgpv35qf0k5ecof8siurp4lqgi.apps.googleusercontent.com',
    iosClientId: '162244151198-ku0iu6f6p9je5l0s9eb7m2k08vdt5esp.apps.googleusercontent.com',
    iosBundleId: 'app.hookedfangtagebuch',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcBos9W8UY1YJ82ogejEHVGFZPkEy7dSM',
    appId: '1:162244151198:web:47096256271b8cee45f88f',
    messagingSenderId: '162244151198',
    projectId: 'hooked-fangtagebuch',
    authDomain: 'hooked-fangtagebuch.firebaseapp.com',
    storageBucket: 'hooked-fangtagebuch.firebasestorage.app',
  );

}