enum MissionType { daily, weekly, seasonal, achievement }

enum MissionStatus { locked, active, completed }

class Mission {
  final String id;
  final String title;
  final String description;
  final String emoji;
  final MissionType type;
  final int pointsReward;
  final MissionStatus status;
  final int progress;
  final int goal;
  final DateTime? completedAt;
  final DateTime? expiresAt;

  const Mission({
    required this.id,
    required this.title,
    required this.description,
    required this.emoji,
    required this.type,
    required this.pointsReward,
    required this.status,
    required this.progress,
    required this.goal,
    this.completedAt,
    this.expiresAt,
  });

  double get progressPercent =>
      goal > 0 ? (progress / goal).clamp(0.0, 1.0) : 0;
  bool get isCompleted => status == MissionStatus.completed;
  bool get isExpired => expiresAt != null && DateTime.now().isAfter(expiresAt!);

  Mission copyWith({
    String? id,
    String? title,
    String? description,
    String? emoji,
    MissionType? type,
    int? pointsReward,
    MissionStatus? status,
    int? progress,
    int? goal,
    DateTime? completedAt,
    DateTime? expiresAt,
  }) => Mission(
    id: id ?? this.id,
    title: title ?? this.title,
    description: description ?? this.description,
    emoji: emoji ?? this.emoji,
    type: type ?? this.type,
    pointsReward: pointsReward ?? this.pointsReward,
    status: status ?? this.status,
    progress: progress ?? this.progress,
    goal: goal ?? this.goal,
    completedAt: completedAt ?? this.completedAt,
    expiresAt: expiresAt ?? this.expiresAt,
  );

  Map<String, dynamic> toMap() => {
    'id': id,
    'title': title,
    'description': description,
    'emoji': emoji,
    'type': type.name,
    'points_reward': pointsReward,
    'status': status.name,
    'progress': progress,
    'goal': goal,
    'completed_at': completedAt?.toIso8601String(),
    'expires_at': expiresAt?.toIso8601String(),
  };

  factory Mission.fromMap(Map<String, dynamic> map) => Mission(
    id: map['id'] as String,
    title: map['title'] as String,
    description: map['description'] as String,
    emoji: map['emoji'] as String,
    type: MissionType.values.firstWhere((e) => e.name == map['type']),
    pointsReward: map['points_reward'] as int,
    status: MissionStatus.values.firstWhere((e) => e.name == map['status']),
    progress: map['progress'] as int,
    goal: map['goal'] as int,
    completedAt: map['completed_at'] != null
        ? DateTime.parse(map['completed_at'] as String)
        : null,
    expiresAt: map['expires_at'] != null
        ? DateTime.parse(map['expires_at'] as String)
        : null,
  );
}

class MissionSeed {
  static List<Mission> defaultMissions() {
    final now = DateTime.now();
    final todayEnd = DateTime(now.year, now.month, now.day, 23, 59, 59);
    final weekEnd = now.add(Duration(days: 7 - now.weekday));
    final seasonEnd = _seasonEnd(now);

    return [
      Mission(
        id: 'daily_first_cast',
        title: 'Erster Wurf',
        description: 'Trage deinen ersten Fang des Tages ein',
        emoji: '🌤',
        type: MissionType.daily,
        pointsReward: 50,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_dawn_hunter',
        title: 'Morgengrauen-Jäger',
        description: 'Fange einen Fisch vor 8:00 Uhr',
        emoji: '🌅',
        type: MissionType.daily,
        pointsReward: 100,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_night_owl',
        title: 'Nachteule',
        description: 'Fange einen Fisch nach 22:00 Uhr',
        emoji: '🌙',
        type: MissionType.daily,
        pointsReward: 120,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_photo_proof',
        title: 'Foto-Beweis',
        description: 'Trage heute einen Fang mit Foto ein',
        emoji: '📸',
        type: MissionType.daily,
        pointsReward: 75,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_spot_tagged',
        title: 'Spot verknüpft',
        description: 'Ordne einem heutigen Fang einen Spot zu',
        emoji: '📍',
        type: MissionType.daily,
        pointsReward: 80,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_big_fish',
        title: 'Dickes Ding',
        description: 'Fang mit ≥ 2 kg heute',
        emoji: '⚖️',
        type: MissionType.daily,
        pointsReward: 150,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'weekly_triple_threat',
        title: 'Triple Threat',
        description: '3 verschiedene Raubfischarten diese Woche',
        emoji: '🎯',
        type: MissionType.weekly,
        pointsReward: 300,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_big_five',
        title: 'Big Five',
        description: '5 Fänge in einer Woche eintragen',
        emoji: '🏆',
        type: MissionType.weekly,
        pointsReward: 200,
        status: MissionStatus.active,
        progress: 0,
        goal: 5,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_spot_tour',
        title: 'Hotspot-Tour',
        description: 'Fänge an 3 verschiedenen Spots diese Woche',
        emoji: '🗺️',
        type: MissionType.weekly,
        pointsReward: 250,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_technique_master',
        title: 'Technik-Chamäleon',
        description: '3 verschiedene Führungsstile diese Woche',
        emoji: '🎛️',
        type: MissionType.weekly,
        pointsReward: 300,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_total_weight',
        title: 'Schwergewicht-Woche',
        description: '5 kg Gesamtgewicht in dieser Woche',
        emoji: '🏋️',
        type: MissionType.weekly,
        pointsReward: 350,
        status: MissionStatus.active,
        progress: 0,
        goal: 5,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_dawn_streak',
        title: 'Dämmerungs-Serie',
        description: '2 Fänge vor 8:00 diese Woche',
        emoji: '🌄',
        type: MissionType.weekly,
        pointsReward: 250,
        status: MissionStatus.active,
        progress: 0,
        goal: 2,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'season_zander_hunter',
        title: 'Zander-Saison',
        description: '5 Zander in dieser Saison fangen',
        emoji: '�',
        type: MissionType.seasonal,
        pointsReward: 500,
        status: MissionStatus.active,
        progress: 0,
        goal: 5,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_pike_trophy',
        title: 'Hecht-Trophäe',
        description: 'Hecht mit ≥ 80 cm Länge',
        emoji: '🏆',
        type: MissionType.seasonal,
        pointsReward: 700,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_perch_stack',
        title: 'Barsch-Schwarm',
        description: '10 Barsche diese Saison',
        emoji: '🌟',
        type: MissionType.seasonal,
        pointsReward: 400,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_cold_water',
        title: 'Frostfischer',
        description: 'Fang bei Wassertemperatur unter 6 °C',
        emoji: '🧊',
        type: MissionType.seasonal,
        pointsReward: 450,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'ach_first_spot',
        title: 'Kartograph',
        description: 'Deinen ersten Spot anlegen',
        emoji: '📍',
        type: MissionType.achievement,
        pointsReward: 150,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_micro_jig',
        title: 'Micro-Master',
        description:
            'Barsch mit Micro-Jig fangen (notiere "Micro-Jig" als Köder)',
        emoji: '🦐',
        type: MissionType.achievement,
        pointsReward: 250,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_ten_catches',
        title: 'Veteran',
        description: '10 Fänge gesamt eintragen',
        emoji: '⚔️',
        type: MissionType.achievement,
        pointsReward: 500,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
      ),
      Mission(
        id: 'ach_metric_master',
        title: 'Meter-Marke',
        description: 'Fisch mit ≥ 100 cm Länge fangen',
        emoji: '📏',
        type: MissionType.achievement,
        pointsReward: 1000,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_heavyweight',
        title: 'Schwergewicht-Champion',
        description: 'Fang mit ≥ 5 kg',
        emoji: '💪',
        type: MissionType.achievement,
        pointsReward: 800,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_all_species',
        title: 'Artenvielfalt',
        description:
            'Alle 7 Raubfisch-Arten fangen (Hecht, Zander, Barsch, Wels, Forelle, Huchen, Aal)',
        emoji: '🧬',
        type: MissionType.achievement,
        pointsReward: 1500,
        status: MissionStatus.active,
        progress: 0,
        goal: 7,
      ),
      Mission(
        id: 'ach_twenty_spots',
        title: 'Gewässer-Kartograph',
        description: '20 Spots anlegen',
        emoji: '🧭',
        type: MissionType.achievement,
        pointsReward: 800,
        status: MissionStatus.active,
        progress: 0,
        goal: 20,
      ),
      Mission(
        id: 'ach_photo_collector',
        title: 'Foto-Archivar',
        description: '20 Fänge mit Foto dokumentieren',
        emoji: '🖼️',
        type: MissionType.achievement,
        pointsReward: 500,
        status: MissionStatus.active,
        progress: 0,
        goal: 20,
      ),
      Mission(
        id: 'ach_jig_specialist',
        title: 'Jigging-Spezialist',
        description: '10 Fänge mit Führungsstil „Jiggen"',
        emoji: '🎮',
        type: MissionType.achievement,
        pointsReward: 400,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
      ),
      Mission(
        id: 'ach_century',
        title: 'Jahrhundert',
        description: '100 Fänge insgesamt',
        emoji: '💯',
        type: MissionType.achievement,
        pointsReward: 2000,
        status: MissionStatus.active,
        progress: 0,
        goal: 100,
      ),

      // ─── Zusatz-Daily ────────────────────────────────────────────────────
      Mission(
        id: 'daily_double',
        title: 'Doppelpack',
        description: '2 Fänge an einem Tag',
        emoji: '🎯',
        type: MissionType.daily,
        pointsReward: 120,
        status: MissionStatus.active,
        progress: 0,
        goal: 2,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_species_duo',
        title: 'Arten-Duo',
        description: '2 verschiedene Arten heute',
        emoji: '🎭',
        type: MissionType.daily,
        pointsReward: 150,
        status: MissionStatus.active,
        progress: 0,
        goal: 2,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_early_bird',
        title: 'Early Bird',
        description: 'Fang vor 6:00 Uhr heute',
        emoji: '🐓',
        type: MissionType.daily,
        pointsReward: 180,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_detailed_log',
        title: 'Saubere Doku',
        description: 'Fang heute mit Köder, Farbe und Tiefe',
        emoji: '📒',
        type: MissionType.daily,
        pointsReward: 100,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_note_keeper',
        title: 'Notiz-Nerd',
        description: 'Fang heute mit Notizen eintragen',
        emoji: '📝',
        type: MissionType.daily,
        pointsReward: 60,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),

      // ─── Zusatz-Weekly ───────────────────────────────────────────────────
      Mission(
        id: 'weekly_marathon',
        title: 'Wochen-Marathon',
        description: '10 Fänge in dieser Woche',
        emoji: '🏃',
        type: MissionType.weekly,
        pointsReward: 500,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_five_days',
        title: 'Fünf-Tage-Woche',
        description: 'An 5 verschiedenen Tagen fangen',
        emoji: '📅',
        type: MissionType.weekly,
        pointsReward: 400,
        status: MissionStatus.active,
        progress: 0,
        goal: 5,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_pike_pack',
        title: 'Hecht-Trio',
        description: '3 Hechte in dieser Woche',
        emoji: '🏆',
        type: MissionType.weekly,
        pointsReward: 350,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_notes_log',
        title: 'Tagebuch-Woche',
        description: '3 Fänge mit Notizen diese Woche',
        emoji: '🗒️',
        type: MissionType.weekly,
        pointsReward: 200,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_spot_creator',
        title: 'Neu-Entdecker',
        description: '2 neue Spots in dieser Woche anlegen',
        emoji: '🆕',
        type: MissionType.weekly,
        pointsReward: 300,
        status: MissionStatus.active,
        progress: 0,
        goal: 2,
        expiresAt: weekEnd,
      ),

      // ─── Zusatz-Seasonal ─────────────────────────────────────────────────
      Mission(
        id: 'season_wels',
        title: 'Flussmonster',
        description: 'Einen Wels in dieser Saison fangen',
        emoji: '🌊',
        type: MissionType.seasonal,
        pointsReward: 600,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_forelle_trio',
        title: 'Forellen-Trio',
        description: '3 Forellen in dieser Saison',
        emoji: '❄️',
        type: MissionType.seasonal,
        pointsReward: 450,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_total_length',
        title: 'Meterware',
        description: '300 cm Gesamt-Länge dieser Saison',
        emoji: '📐',
        type: MissionType.seasonal,
        pointsReward: 500,
        status: MissionStatus.active,
        progress: 0,
        goal: 300,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_deep_spots',
        title: 'Tiefenläufer',
        description: '5 Fänge aus > 5 m diese Saison',
        emoji: '🌊',
        type: MissionType.seasonal,
        pointsReward: 400,
        status: MissionStatus.active,
        progress: 0,
        goal: 5,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_ten_spots',
        title: 'Revier-Kenner',
        description: 'Fänge an 10 verschiedenen Spots diese Saison',
        emoji: '🧭',
        type: MissionType.seasonal,
        pointsReward: 600,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
        expiresAt: seasonEnd,
      ),

      // ─── Zusatz-Achievements ─────────────────────────────────────────────
      Mission(
        id: 'ach_huchen',
        title: 'Huchen-Held',
        description: 'Einen Huchen fangen',
        emoji: '⚔️',
        type: MissionType.achievement,
        pointsReward: 700,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_aal',
        title: 'Schlangengrube',
        description: 'Einen Aal fangen',
        emoji: '🌀',
        type: MissionType.achievement,
        pointsReward: 400,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_wels_trophy',
        title: 'Wels-Trophäe',
        description: 'Wels mit ≥ 100 cm Länge',
        emoji: '🏅',
        type: MissionType.achievement,
        pointsReward: 1200,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_all_retrieves',
        title: 'Alleskönner',
        description: 'Alle 6 Führungsstile mindestens einmal fangen',
        emoji: '🎚️',
        type: MissionType.achievement,
        pointsReward: 600,
        status: MissionStatus.active,
        progress: 0,
        goal: 6,
      ),
      Mission(
        id: 'ach_lure_collector',
        title: 'Köder-Sammler',
        description: '10 verschiedene Köder fischen',
        emoji: '🪝',
        type: MissionType.achievement,
        pointsReward: 600,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
      ),

      // ─── Daily Extra 2 ───────────────────────────────────────────────────
      Mission(
        id: 'daily_noon_strike',
        title: 'Mittagshappen',
        description: 'Fang heute zwischen 11:00 und 14:00',
        emoji: '🌞',
        type: MissionType.daily,
        pointsReward: 90,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_drill_fight',
        title: 'Drill-Marathon',
        description: 'Fang mit Kampfdauer > 60 Sekunden',
        emoji: '💥',
        type: MissionType.daily,
        pointsReward: 160,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_precise_log',
        title: 'Präzisions-Log',
        description: 'Fang heute mit Gewicht UND Länge',
        emoji: '🎯',
        type: MissionType.daily,
        pointsReward: 90,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_nature_writer',
        title: 'Natur-Poet',
        description: 'Fang heute mit Notiz ≥ 50 Zeichen',
        emoji: '✒️',
        type: MissionType.daily,
        pointsReward: 120,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),
      Mission(
        id: 'daily_back_to_back',
        title: 'Schlag auf Schlag',
        description: '2 Fänge innerhalb 60 Minuten',
        emoji: '🔁',
        type: MissionType.daily,
        pointsReward: 180,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: todayEnd,
      ),

      // ─── Weekly Extra 2 ──────────────────────────────────────────────────
      Mission(
        id: 'weekly_lure_variety',
        title: 'Köder-Buffet',
        description: '3 verschiedene Köder diese Woche',
        emoji: '🧰',
        type: MissionType.weekly,
        pointsReward: 250,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_slow_approach',
        title: 'Langsam & Listig',
        description: '3 Fänge mit Stil „Slow Roll" diese Woche',
        emoji: '🐢',
        type: MissionType.weekly,
        pointsReward: 220,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_dusk_dawn',
        title: 'Randzeit-Spezialist',
        description: 'Diese Woche je 1 Fang vor 8:00 und nach 20:00',
        emoji: '🌆',
        type: MissionType.weekly,
        pointsReward: 300,
        status: MissionStatus.active,
        progress: 0,
        goal: 2,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_heavy_single',
        title: 'Dicker Brocken',
        description: 'Einzelfang ≥ 3 kg diese Woche',
        emoji: '🏋️‍♂️',
        type: MissionType.weekly,
        pointsReward: 350,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: weekEnd,
      ),
      Mission(
        id: 'weekly_color_variety',
        title: 'Farbspiel',
        description: '3 verschiedene Köder-Farben diese Woche',
        emoji: '🎨',
        type: MissionType.weekly,
        pointsReward: 220,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: weekEnd,
      ),

      // ─── Seasonal Extra 2 ────────────────────────────────────────────────
      Mission(
        id: 'season_ice_warrior',
        title: 'Eis-Krieger',
        description: '3 Fänge bei Wassertemperatur < 4 °C',
        emoji: '❄️',
        type: MissionType.seasonal,
        pointsReward: 600,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_summer_heat',
        title: 'Hitze-Held',
        description: 'Fang bei Wassertemperatur > 22 °C',
        emoji: '🔥',
        type: MissionType.seasonal,
        pointsReward: 350,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_all_weekdays',
        title: 'Sieben-Tage-Jäger',
        description: 'Diese Saison an jedem Wochentag mind. 1 Fang',
        emoji: '📆',
        type: MissionType.seasonal,
        pointsReward: 700,
        status: MissionStatus.active,
        progress: 0,
        goal: 7,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_fifty_photos',
        title: 'Fotograf der Saison',
        description: '50 Fänge mit Foto in dieser Saison',
        emoji: '📷',
        type: MissionType.seasonal,
        pointsReward: 700,
        status: MissionStatus.active,
        progress: 0,
        goal: 50,
        expiresAt: seasonEnd,
      ),
      Mission(
        id: 'season_night_fish',
        title: 'Mitternachts-Angler',
        description: '3 Fänge zwischen 0:00 und 4:00',
        emoji: '🌌',
        type: MissionType.seasonal,
        pointsReward: 550,
        status: MissionStatus.active,
        progress: 0,
        goal: 3,
        expiresAt: seasonEnd,
      ),

      // ─── Achievement Extra 2 ─────────────────────────────────────────────
      Mission(
        id: 'ach_weight_sum_50kg',
        title: 'Halbe Tonne',
        description: '50 kg Gesamtgewicht gefangen',
        emoji: '🏋️',
        type: MissionType.achievement,
        pointsReward: 1500,
        status: MissionStatus.active,
        progress: 0,
        goal: 50,
      ),
      Mission(
        id: 'ach_length_sum_10m',
        title: 'Zehn-Meter-Klub',
        description: '1000 cm kumulierte Fischlänge',
        emoji: '📐',
        type: MissionType.achievement,
        pointsReward: 900,
        status: MissionStatus.active,
        progress: 0,
        goal: 1000,
      ),
      Mission(
        id: 'ach_long_drill',
        title: 'Eiserner Arm',
        description: 'Drill-Dauer ≥ 5 Minuten bei einem Fang',
        emoji: '⏱️',
        type: MissionType.achievement,
        pointsReward: 800,
        status: MissionStatus.active,
        progress: 0,
        goal: 1,
      ),
      Mission(
        id: 'ach_color_collector',
        title: 'Farb-Archiv',
        description: '10 verschiedene Köder-Farben fangen',
        emoji: '🌈',
        type: MissionType.achievement,
        pointsReward: 600,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
      ),
      Mission(
        id: 'ach_spot_regular',
        title: 'Stammgast',
        description: '10 Fänge am selben Spot',
        emoji: '🪑',
        type: MissionType.achievement,
        pointsReward: 700,
        status: MissionStatus.active,
        progress: 0,
        goal: 10,
      ),
    ];
  }

  static DateTime _seasonEnd(DateTime now) {
    final m = now.month;
    if (m >= 3 && m <= 5) return DateTime(now.year, 5, 31, 23, 59, 59);
    if (m >= 6 && m <= 8) return DateTime(now.year, 8, 31, 23, 59, 59);
    if (m >= 9 && m <= 11) return DateTime(now.year, 11, 30, 23, 59, 59);
    final y = m == 12 ? now.year + 1 : now.year;
    return DateTime(y, 2, 28, 23, 59, 59);
  }
}
